### ISSUE TITLE
Compress button not scroll-able for screen less than 14 inch 

### ISSUE THREAD

**Issue by NgatiaFrankline** [hkdb/Densify#5]
My laptop is hp probook 440 G5. Its a 14inch Screen. I have installed Densify. However i cannot see the Compress now button. Its not scrollable. See attached screenshot. 

![Screenshot from 2020-03-14 18-50-41](https://user-images.githubusercontent.com/42550912/76685594-03659200-6626-11ea-8bf6-840dfd5472af.png)

**Comment by TheNomad11** [comment]
Same issue here, but it seems to be an abandoned project, no updates for two years...

**Comment by hkdb** [comment]
Hey guys,

Sorry for the late reply on this. "Life got in the way." It looks like what's happening is that you both are running on pretty low resolution? I am also on a 14" but doing 1080p so this does not happen.

After doing some testing, it seems that when I set the resolution to 1280x720 (16:9) resolution (or lower), I then finally experience the same issue as yourself. I don't have a device that runs lower than 1080p now-a-days so I never noticed that before.

In the latest release, I have put together a hack that basically doesn't show the logo and shrinks the app window upon detecting display height of below 720.

You can find that in the master branch now or https://github.com/hkdb/Densify/releases/tag/v0.3.0

Let me know if that fixes the problem for you.

Thanks!

**Comment by TheNomad11** [comment]
Thanks for your work! But nothing changed for me with the new version. My screen resolution is 1366x768, and the logo still shows up

**Comment by hkdb** [comment]
@TheNomad11 Thanks for the quick feedback! I have just released v0.3.1 that will launch in low resolution mode when it detects anything below x800 instead of x730. Can you give that a whirl?

Thanks!

**Comment by TheNomad11** [comment]
Perfect now, thanks a lot!!!
